"""empty message

Revision ID: 07893ee9e5b4
Revises: 64eaba4e9fcc
Create Date: 2018-12-17 15:21:24.171160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07893ee9e5b4'
down_revision = '64eaba4e9fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('amplification', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'amplification')
    # ### end Alembic commands ###
