"""j_C and res Document

Revision ID: 4abeedf989f7
Revises: 733006aa6a2c
Create Date: 2019-01-14 13:14:53.554875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4abeedf989f7'
down_revision = '733006aa6a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('j_C', sa.Float(), nullable=True))
    op.add_column('document', sa.Column('res', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'res')
    op.drop_column('document', 'j_C')
    # ### end Alembic commands ###
