"""Document

Revision ID: 528675969d33
Revises: 
Create Date: 2018-12-08 14:12:12.224067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528675969d33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    # ### end Alembic commands ###
