"""empty message

Revision ID: 59dfcf5e8839
Revises: 
Create Date: 2019-01-14 11:51:41.746816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59dfcf5e8839'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('substrate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('substratename', sa.String(length=32), nullable=True),
    sa.Column('Au_layer', sa.Integer(), nullable=True),
    sa.Column('YBCO_layer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bridge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('substrate_id', sa.Integer(), nullable=True),
    sa.Column('bridgename', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['substrate_id'], ['substrate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bridge_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.Column('remove_offset', sa.Boolean(), nullable=True),
    sa.Column('remove_ohm', sa.Boolean(), nullable=True),
    sa.Column('amplification', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bridge_id'], ['bridge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    op.drop_table('bridge')
    op.drop_table('substrate')
    # ### end Alembic commands ###
