"""empty message

Revision ID: 64eaba4e9fcc
Revises: 528675969d33
Create Date: 2018-12-10 14:12:40.845606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64eaba4e9fcc'
down_revision = '528675969d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('remove_offset', sa.Boolean(), nullable=True))
    op.add_column('document', sa.Column('remove_ohm', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'remove_ohm')
    op.drop_column('document', 'remove_offset')
    # ### end Alembic commands ###
