"""j_C and res in bridge

Revision ID: 733006aa6a2c
Revises: 59dfcf5e8839
Create Date: 2019-01-14 13:02:11.668441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733006aa6a2c'
down_revision = '59dfcf5e8839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge', sa.Column('j_C', sa.Float(), nullable=True))
    op.add_column('bridge', sa.Column('res', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bridge', 'res')
    op.drop_column('bridge', 'j_C')
    # ### end Alembic commands ###
